Step01. 쿼리 최적화
next-step/infra-subway-db pull request #15
Opened 2022-10-05 02:09 UTC by Miniminis

동규님, 안녕하세요 🙌
쿼리를 짜는데 생각보다 시간이 오래걸렸습니다 😭 
시간 조건도 맞추지 못했지만, 혼자 계속 고민해서 나아질 것이 없을 것 같아서 리뷰 요청을 드립니다. 

크게 쿼리를 두 가지 범위로 나누어서 구성했는데, 이게 맞을지 잘 모르겠네요. 
1. 활동중인(Active) 부서의 현재 부서관리자 중 연봉 상위 5위안에 드는 사람들 
2. 최근에 각 지역별로 언제 퇴실했는지 조회

` 연봉 상위 5위안에 드는 사람들` 을 뽑는 과정에서 시간이 좀 걸렸는데, 연봉 테이블만으로 뽑으려다보니 막상 근무중이지 않거나 메니저가 아닌 사람들이 섞이게 되어서 복잡하게 중첩으로 조인을 하는 기다란 쿼리가 완성되어버렸습니다...! 

한눈에 보기에도 가독성도 안좋고 조회시간도 긴데, 어떻게 개선을 할 수 있을지 조언 주시면, 개선해보겠습니다!

2022-10-05 17:38 UTC, brainbackdoor approved these changes
1단계 미션 진행하느라 고생하셨어요~ 👍🏻 
피드백 남겨두었는데요. 참고하셔서 다시 수정해보시겠어요~
진행하다 궁금한 점 있으시면 질문주세요~ 🙏🏻

2022-10-05 17:38 UTC, brainbackdoor commented on sqls/23306-data-tuning-queryoptimization-view.sql
> +    limit 5;
이 구간이 너무 느린데요.
position 테이블을 조인하는 것보다 manager 테이블을 조인하는 것은 어떨까요?

```sql
SELECT id, annual_income FROM 
(
	SELECT employee_id, end_date FROM manager WHERE end_date >= current_date()
) AS m 
INNER JOIN (
	SELECT id, annual_income, end_date FROM salary
) AS s on m.employee_id = s.id AND s.end_date >= current_date()
ORDER BY annual_income desc 
limit 5;
```

2022-10-05 17:38 UTC, brainbackdoor commented on sqls/23306-data-tuning-queryoptimization-view.sql
> +    limit 5;
쿼리 작성은 접근하신 단계로 진행하시면 되어요~

2022-10-05 17:39 UTC, brainbackdoor requested changes
1단계 미션 진행하느라 고생하셨어요~ 👍🏻
피드백 남겨두었는데요. 참고하셔서 다시 수정해보시겠어요~
진행하다 궁금한 점 있으시면 질문주세요~ 🙏🏻

2022-10-05 23:56 UTC, Miniminis commented
동규님 🙌 피드백 감사드립니다! 
동규님 쿼리를 보니까 아래와 같이 두 가지 점을 놓치고 있었던 것 같습니다. 
1. from 절 자체에 아예 서브쿼리로 기준 테이블을 둔다. 
- 왜인지는 모르겠지만 from 절에 서브쿼리를 안쓰려고 무의식적으로 생각했던 것 같습니다 💦
- 동규님 작성해주신대로 하니 훨씬 간단해지네요 😀

2. join 문의 on 절과 함께 AND 로 필터링 조건을 걸 수 있다.  
- 이 부분은 기존에 없던 지식이었는데 새롭게 알게 되었습니다. 감사합니다 🙏

위와 같이 수정 진행해보았는데 기존의 4s대에서 2s로 시간은 줄어들었으나, 0.2s 기준은 만족하지 못했네요 🥹

2022-10-06 17:16 UTC, brainbackdoor requested changes
피드백 반영 확인했어요~ 👍🏻 
추가로 몇가지 생각해볼 지점이 있어 피드백 남겨두었어요~
좋은 밤 보내세요~

2022-10-06 17:16 UTC, brainbackdoor commented on README.md
> +    group by employee_id, region
```sql
SELECT employee_id, region, COUNT(*) FROM tuning.record WHERE record_symbol = 'O' GROUP BY employee_id,region HAVING COUNT(*) >1;
```
한 지역에 반복적으로 갔던 케이스가 없어서, 이 부분은 집계함수를 사용하지 않아도 될듯합니다.

2022-10-06 17:16 UTC, brainbackdoor commented on README.md
> +    group by employee_id, region
<img width="1119" alt="스크린샷 2022-10-07 오전 2 10 11" src="https://user-images.githubusercontent.com/29951288/194376271-d76c4efd-e9be-4fd6-a3e3-07d76e84c653.png">
- 현재 위와 같은 구조인데요. LEFT JOIN을 INNER JOIN으로 한번 변경해보시겠어요?
- 추가적으로 이번 단계의 핵심은, record 테이블의 329467 row 를 탐색하는 비용을 어떻게 줄일 수 있는지가 관건이에요. 아래와 같이 모수 테이블의 크기를 줄여 탐색 비용을 줄여볼 수 있어요~
<img width="1198" alt="스크린샷 2022-10-07 오전 2 10 54" src="https://user-images.githubusercontent.com/29951288/194376385-503a9a17-b73a-4c36-af48-9ca87c4cb4c3.png">

2022-10-09 08:03 UTC, Miniminis commented on README.md
> +    group by employee_id, region
집계함수가 필요할지 한번만 조회해서 확인해봤다면 좋았을텐데, 아쉽군요 🥹
동규님 피드백 덕분에 쿼리가 점점 빨라지고 있습니다 :) 감사합니다 🙌

2022-10-10 01:53 UTC, brainbackdoor requested changes
피드백 반영 잘해주셨네요~ 👍🏻 
추가로 피드백 몇가지 더 남겨두었어요~ ㅎㅎ;
좋은 하루 보내세요~

2022-10-10 01:53 UTC, brainbackdoor commented on README.md
> +LEFT JOIN record r on r.employee_id = top_m.employee_id AND r.record_symbol = 'O';
```suggestion
INNER JOIN record r on r.employee_id = top_m.employee_id AND r.record_symbol = 'O';
```

https://github.com/next-step/infra-subway-db/pull/15#discussion_r989298895

2022-10-10 01:53 UTC, brainbackdoor commented on README.md
> +			and lower(d.note) = 'active'
```suggestion
			and d.note = 'active'
```
MySQL은 대소문자를 구분하지 않아요. 그런데 여기서 컬럼을 변경하면서 인덱스를 활용하지 않게되네요
그리고 인덱스를 사용하면서 커버링 인덱스 효과까지 발생합니다.
숨겨두었던 부분들을 직접 고민하고 해결해보셨으면 싶었는데 살짝 아쉽네요

2022-10-10 09:34 UTC, Miniminis commented on README.md
> +			and lower(d.note) = 'active'
앗...! 그랬었군요 😭 큰 구조를 신경쓰느라 그 부분을 완전히 놓쳐버린 것 같네요..! 감사합니다 동규님😄

2022-10-10 15:41 UTC, brainbackdoor approved these changes
피드백 반영 확인했어요~ 👍🏻 
미션 진행하느라 고생하셨어요~ 
이번 단계는 여기서 머지할게요~

2022-10-10 15:41 UTC, merged